export { default as userRoutes } from "./auth.routes";
export { default as addressRoutes } from "./address.routes";
export { default as categoryRoutes } from "./category.routes";
export { default as productRoutes } from "./product.routes";
export { default as cartRoutes } from "./cart.routes";
export { default as wishlistRoutes } from "./wishlist.routes";
export { default as orderRoutes } from "./order.routes";
export { default as ratingRoutes } from "./rating.routes";
export { default as webhookRoutes } from "./webhook.routes";
